title: Jekyll Eleventy Astro JS SSG Website Developer
description: Creativitas Web Dev Static Site Generator Web Dev
favicon: /assets/img/creativitaswebdev.webp
intro: www.fiverr.com/creativitas
link: https://www.fiverr.com/creativitas
menu1: Services
menu2: Projects
menu3: Themes
menu4: Codes
locale: en_EN
url: 'https://creativitas.github.io'
#baseurl: ''
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag